# Loading Packages

In [1]:
import Pkg
basedir = "../"
Pkg.activate(basedir)
using BenchmarkTools

input = readlines(basedir*"data/input_06.txt")

  Activating project at `/uufs/chpc.utah.edu/common/home/sdss42/sdsswork/users/u6039752-1/software/AdventOfCode2023.jl`


2-element Vector{String}:
 "Time:        44     82     69     81"
 "Distance:   202   1076   1138   1458"

In [3]:
input_test = readlines(basedir*"data/input_06t.txt")

2-element Vector{String}:
 "Time:      7  15   30"
 "Distance:  9  40  200"

# Part 1

In [14]:
time_vec = parse.(Int,split(input_test[1]," ",keepempty=false)[2:end])
d_vec = parse.(Int,split(input_test[2]," ",keepempty=false)[2:end])

3-element Vector{Int64}:
   9
  40
 200

In [16]:
function get_d_traveled(hold_time,total_time)
    return hold_time*(total_time-hold_time)
end

function get_d_traveled_vec(total_time)
    return get_d_traveled.(1:(total_time-1),Ref(total_time))
end

get_d_traveled_vec (generic function with 1 method)

In [18]:
function get_num_ways2win(total_time,dmin)
    vec_ways = get_d_traveled_vec(total_time)
    return count(dmin .< vec_ways)
end

get_num_ways2win (generic function with 1 method)

In [21]:
function solution(input)
    time_vec = parse.(Int,split(input[1]," ",keepempty=false)[2:end])
    d_vec = parse.(Int,split(input[2]," ",keepempty=false)[2:end])
    num_race = length(time_vec)
    out_vec = zeros(Int,num_race)
    for i = 1:num_race
        out_vec[i] = get_num_ways2win(time_vec[i],d_vec[i])
    end
    return prod(out_vec)
end

solution (generic function with 1 method)

In [22]:
solution(input_test)

288

In [23]:
solution(input)

588588

In [39]:
@benchmark solution(input)

BenchmarkTools.Trial: 10000 samples with 8 evaluations.
 Range (min … max):  3.659 μs … 243.531 μs  ┊ GC (min … max): 0.00% … 96.30%
 Time  (median):     3.793 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.137 μs ±   6.274 μs  ┊ GC (mean ± σ):  3.92% ±  2.55%

  ▁▅▇██▇▆▅▄▂▁                   ▁▁ ▁▁▁▂▁▂▁▂▁▁▁▁▁▁             ▂
  ███████████▇▆▆▆▆▆▆▇▇▇▇▇▇██████████████████████████████▇▇▆▅▆ █
  3.66 μs      Histogram: log(frequency) by time      5.37 μs <

 Memory estimate: 4.00 KiB, allocs estimate: 22.

# Part 2

In [32]:
time_vec = parse(Int,join(split(input_test[1]," ",keepempty=false)[2:end]))
d_vec = parse(Int,join(split(input_test[2]," ",keepempty=false)[2:end]))

940200

In [33]:
get_num_ways2win(time_vec,d_vec)

71503

In [34]:
time_vec = parse(Int,join(split(input[1]," ",keepempty=false)[2:end]))
d_vec = parse(Int,join(split(input[2]," ",keepempty=false)[2:end]))

202107611381458

In [35]:
get_num_ways2win(time_vec,d_vec)

34655848

In [36]:
time_vec

44826981

In [37]:
d_vec

202107611381458

In [38]:
@benchmark get_num_ways2win(time_vec,d_vec)

BenchmarkTools.Trial: 34 samples with 1 evaluation.
 Range (min … max):  137.516 ms … 162.111 ms  ┊ GC (min … max):  0.10% … 12.51%
 Time  (median):     148.955 ms               ┊ GC (median):    13.63%
 Time  (mean ± σ):   149.713 ms ±   3.700 ms  ┊ GC (mean ± σ):  13.24% ±  2.33%

                            ▆▆█▁▁▃                               
  ▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄██████▄▁▄▁▄▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▁▁▁▁▄ ▁
  138 ms           Histogram: frequency by time          162 ms <

 Memory estimate: 347.35 MiB, allocs estimate: 7.

obviously one could right better code to find first and then find last... but sometimes you just need to do what works fast and recognize when the numbers are not too big.